//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class MingDynastyDBEntities : DbContext
{
    public MingDynastyDBEntities()
        : base("name=MingDynastyDBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<AdminUser> AdminUser { get; set; }
    public virtual DbSet<MingBanner> MingBanner { get; set; }
    public virtual DbSet<MingCulture> MingCulture { get; set; }
    public virtual DbSet<MingEmperor> MingEmperor { get; set; }
    public virtual DbSet<MingEvent> MingEvent { get; set; }
    public virtual DbSet<MingFigure> MingFigure { get; set; }
    public virtual DbSet<MingMessage> MingMessage { get; set; }
    public virtual DbSet<MingSystemArticle> MingSystemArticle { get; set; }
    public virtual DbSet<MingUser> MingUser { get; set; }
}
