//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AdminUser
{
    public int ID { get; set; }
    public string UserName { get; set; }
    public string Pwd { get; set; }
}

public partial class MingBanner
{
    public int ID { get; set; }
    public string Title { get; set; }
    public string ImageUrl { get; set; }
    public string LinkUrl { get; set; }
    public Nullable<int> Sort { get; set; }
}

public partial class MingCulture
{
    public int ID { get; set; }
    public string Title { get; set; }
    public string Category { get; set; }
    public string Author { get; set; }
    public string Cover { get; set; }
    public string Content { get; set; }
    public Nullable<int> Sort { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
}

public partial class MingEmperor
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MingEmperor()
    {
        this.MingEvent = new HashSet<MingEvent>();
    }

    public int ID { get; set; }
    public string EmpName { get; set; }
    public string ReignTitle { get; set; }
    public string TempleName { get; set; }
    public string ReignYears { get; set; }
    public string Intro { get; set; }
    public string Period { get; set; }
    public Nullable<int> Sort { get; set; }
    public string Avatar { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MingEvent> MingEvent { get; set; }
}

public partial class MingEvent
{
    public int ID { get; set; }
    public string EventName { get; set; }
    public Nullable<int> EventYear { get; set; }
    public Nullable<int> EmpID { get; set; }
    public string Content { get; set; }
    public string Period { get; set; }
    public Nullable<int> Sort { get; set; }

    public virtual MingEmperor MingEmperor { get; set; }
}

public partial class MingFigure
{
    public int ID { get; set; }
    public string Name { get; set; }
    public string Category { get; set; }
    public Nullable<int> BirthYear { get; set; }
    public Nullable<int> DeathYear { get; set; }
    public string IdentityTitle { get; set; }
    public string Achievement { get; set; }
    public string Avatar { get; set; }
    public string Intro { get; set; }
    public Nullable<int> Sort { get; set; }
}

public partial class MingMessage
{
    public int ID { get; set; }
    public Nullable<int> UserID { get; set; }
    public string NickName { get; set; }
    public string Content { get; set; }
    public string ReplyContent { get; set; }
    public Nullable<bool> IsTop { get; set; }
    public Nullable<bool> IsAnonymous { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
    public Nullable<System.DateTime> ReplyTime { get; set; }

    public virtual MingUser MingUser { get; set; }
}

public partial class MingSystemArticle
{
    public int ID { get; set; }
    public string Title { get; set; }
    public string Category { get; set; }
    public string Content { get; set; }
    public Nullable<bool> IsTop { get; set; }
    public Nullable<bool> IsShow { get; set; }
    public Nullable<System.DateTime> CreateTime { get; set; }
}

public partial class MingUser
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MingUser()
    {
        this.MingMessage = new HashSet<MingMessage>();
    }

    public int ID { get; set; }
    public string UserName { get; set; }
    public string NickName { get; set; }
    public string Pwd { get; set; }
    public string Email { get; set; }
    public string Avatar { get; set; }
    public Nullable<System.DateTime> RegisterTime { get; set; }
    public Nullable<System.DateTime> LastLoginTime { get; set; }
    public Nullable<bool> Status { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MingMessage> MingMessage { get; set; }
}
